language: ruby
cache: bundler
rbenv:
- 2.5.3
before_install:
- gem install bundler
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: PGG2yVPtF7S4I1JUrl+5lzipGF2suzqfxbOP4Qa31jsihKR3L2pO+l3EqYCSjxNOnKAHBtgqc3SMA1bILDMkoWA2IHVpGZ08Ib9eldHFZGJ2Gof8DKRQGmrK9Em032YC/r3Vyw68TwRs06w899axKmRAkdEUazUFfifwErcXQ3v8TCikfxd4kv0bNz6UcwSleDej9VYhbC5MkF/DTGPkz2w4A6tkwMsP99lR6hoqHIVRIWd3QJfsLlPG3iI2InqQZuUTC0YEDnhx6me2xOfX3YAzZljM3fMCWdQS6PN0XL7WyuzeU2zWUJqZ3skWpg+ZWkyi0QSR8HRGsCnu0o0yGRiMgFfMV6UpeqCqm3p4bOJyiZE4iwoyzO9z0kRDQXjvJt9vVCRYwF+YMn5ztBggpaaDhS92yKsvhOZhSSs4ycTvyBf3sN87KJNCTQp7fB6aMe3FX636Fj3yiGyd+p4xqB33NQDXvh8ec2NZfh91DSLX67U1Ke4nbfhIMZaDdrfVaWQ1W6xYnBjmJrTY3/HxcgrLUmYoHNSTqV4ZYM8kvmstypeatymlBchzoswoKeAIsNZBjiYLCH0/c//b7hlyvEpFQOk5vO+/u4S+iLmqGOopz5Sir+901Wf+EjBLDAjsELclMj181dDJVC//KOjOkToNQTcVfSgrK72m8pKddfo=
  app: i-scream-arcade
  on: 
    repo: perryr16/i-scream-arcade
  run: rails db:migrate
